313 payment for spent gas at the end of each iteration (#320)
* Introduce gas_used_and_paid and number_of_payments

* Fix: error[E0308]: mismatched types

* Operator transfers only 201 NEON to an eth user token account for tests

* Fix: error: unused variable: `number_of_payments`

* Check in CI that only two of the three transactions are charged.

* error[E0597]: `account_storage` does not live long enough

* Error: Instruction references an unknown account

* Error: error[E0621]: explicit lifetime required in the type of `source_account`

* Use user sol info from instruction account infos

* Where to save the value of the paid gas?

* Refactor to use all accounts

* Turn on all tests

* Use comma

* Fix test_deploy.py

* Fix test_event.pyy

* Fix test_eth_token.py

* Refactor: introduce user_pays_operator_impl to make the code more clear

* Refactor: debug output

* Fixing test_nested_call.py...

* Fix: error: unused variable: `number_of_payments`

* Add solana transaction log for gas_used_and_paid

* User does not pay for the iteration when used_gas < gas_used_and_paid

* Turn on all tests

* Fix test_rw_block.py

* Fix test_solidity_precompiles.py

* Turn off some tests

* Fix after the merge

* Check with the proxy branch: "313-Payment_for_spent_gas_at_the_end_of_each_iteration"

* Add checks of payment for spent gas at the end of each iteration

* revert to "${PROXY_BRANCH:-develop}"

* At the start of the iterative transaction, we check that (gas_price * gas_limit) <{user neon-token account balance}
and if the condition is not met
return ProgramError :: InsufficientFunds.

On the continuation of the iterative transaction, we check that (gas_price * (gas_limit - gas_paid) <{user neon-token account balance}.
and if the condition is not met
we complete the transaction
freeing storage
funds spent for previous iterations are not returned to the user
return ProgramError :: InsufficientFunds.

For iteration we take only for total_used_gas / 2

* Revert "revert to "${PROXY_BRANCH:-develop}""

This reverts commit 304bdb6730143d653fcbb8974a9a9b649f09cbef.

* Take into account min_transfer_value

* Add a test to check insufficient funds for instruction

* Fix: invalid program argument when user does not pay for this iteration

* Rename to add_gas_has_been_paid

* Fix half_of_total_used_gas

* Remove check_enough_funds_impl

* Fixing test_transaction.py

* Introduce a new version of the instruction 11(0x0B) -> 18(0x13)

* Introduce a new version of the instruction 11(0x0B) -> 18(0x12)

* Remove checking enough funds for non iterative transactions.

* Remove checking gas_to_be_paid > gas_limit

* Use https://doc.rust-lang.org/std/primitive.u64.html#method.saturating_sub

* Fix: error: unused import: `msg`

* Rename to _number_of_payments

* Use debug_print! for logs

* Introduce a new version of the instruction 11(0x0B) -> 18(0x12)

* Introduce a new version of the instruction 09(0x09) -> 19(0x13)

* User should pay on the first iteration of deployment

* Fix error with using executor_state without declared

* Fix tests

* Fix tests with new instructions

* Decrease amount of arguments

* Underscore of useless vars

* Lists of account are defferent for instructions: 10, 13, 14

* Reduced the chain of calling

* Reorder account metas in do_begin

* Refactoring

* Refactoring

* Refactoring to use
type UsedGas = u64;
type EvmResults = (ExitReason, Vec<u8>, Option<ApplyState>);
type CallResult = Result<(Option<EvmResults>,UsedGas), ProgramError>;

* Refactor add_gas_has_been_paid

* Refactor to make the code compact

* Introduce a function user_pays_operator_for_iteration

* Revert to "${PROXY_BRANCH:-develop}

* Return to the original version with a lot of arguments.

* Remove complete_transaction

* Revert "Revert to "${PROXY_BRANCH:-develop}"

This reverts commit 2de64f8f38ea4108c4b9a8185f1b3a6fda16cf8b.

* Fix after merge
Replace a new version of the instruction 18(0x12) -> 22(0x16)

* Removed unnecessary line breaks to improve readability.

* Fix after the previous merge

* Revert "Revert "Revert to "${PROXY_BRANCH:-develop}""

This reverts commit 9808fb8d7565cf98fce413496d4639acf89b5911.