122 estimate gas on deploy a contract (evm_loader, neon-cli) (#143)
* Introduce is_valid_h160_or_deploy, h160_or_deploy_of

* Fix error: this creates an owned instance just for comparison

* Debug info

* Tests shown that transact_create estimates 10 times less than required
estimation was 175636
real used gas was 1732075

* Make public executor an executor_state

* Add /// Todo: document
    /// # Panics
    /// Todo: document Panics
    /// # Errors
    /// Todo: document Errors

153 added TODO items

* Use evm_loader::executor instead of evm::executor::StackExecutor

* Use 99_999_996 as limit on gas to estimate

* Fix build after the merge of origin/develop

* Introduce verbose_flags for neon_cli

* Turn off test_successful_cli_emulate

* Use v1.7.6-resources

* PROXY_BRANCH:-122-estimate_gas_on_deploy_a_contract

* PROXY_BRANCH:-"122-estimate_gas_on_deploy_a_contract"

* PROXY_BRANCH:-122_estimate_gas_on_deploy_a_contract

* PROXY_BRANCH:-develop

* PROXY_BRANCH:-122_estimate_gas_on_deploy_a_contract

* branch: "122_estimate_gas_on_deploy_a_contract"

* Use --rmi type
https://docs.docker.com/compose/reference/down/

* v1.7.6 -> v1.6.9

* Add call_begin

* v1.6.9

* Refactor command_emulate

* branch: "122-estimate_gas_on_deploy_a_contract"

* Debug get_ether_account_nonce

* Use solana_address to get trx count

* FN get_ether_account_nonce return 0 if an account was not found

* gas_limit = u64::MAX>>11;
u64::MAX is too large, remix gives this error:

Gas estimation errored with the following message.
Number can only safely store up to 53 bits

* gas_limit = u64::MAX>>32;

* gas_limit = u64::MAX>>11;

* Remove double record_cost of gas

* Fix error: unused variable: `gas_limit`

* Use is_amount to validate 'value' arg

* Use value_of to get 'value' arg

* Introduce is_amount_u256

* Add value to debug messages

* gas_limit = 50_000_000 to decrease the effect of endless cycle

* Use "None" if <DATA> is empty on emulate

* Transaction data or 'None'

* Adjust code to the new signature of fn get_ether_account_nonce

* gas_limit will be used in create_begin instead of None

* Fix error[E0425]: cannot find value `_gas_limit` in this scope

* "${PROXY_BRANCH:-develop}"

* Use clippy::missing_panics_doc, clippy::missing_errors_doc

* to_lowercase() == "none"

* branch: "122-estimate_gas_on_deploy_a_contract"

* "${PROXY_BRANCH:-develop}"